#!/bin/bash
source $(dirname $0)/config
PWD=$(dirname $0)

source $(dirname $0)/bg_rotate
SUM_MEM_VALUE=`free -h | grep Mem |tail -n 1 | gawk '{print $2}'`
MEM_USAGE=`free -h | grep Mem |tail -n 1 | gawk '{print $3}'`
MEM_PERCENT=`free | grep Mem | awk '{print $3/$2 * 100.0}'`
CPU_USAGE=`top -bn 2 -d 0.01 | grep '^%Cpu' | tail -n 1 | gawk '{print $2+$4+$6}'`
CPU_USAGE=`printf %03d $CPU_USAGE`
MEM_PERCENT=`printf %03.02f $MEM_PERCENT`
CPU_TEMP=`sensors | grep Physical | gawk '{print $4}'`

CPU_INFO="  ^fg(#19B5FE)^i(./dzen_icons/cpu.xbm) ^fg(#F8F8F8)${CPU_USAGE} %"
MEM_INFO="  ^fg(#36D7B7)^i(./dzen_icons/mem.xbm) ^fg(#F8F8F8)$MEM_USAGE($MEM_PERCENT %)"
CPU_TEMP_INFO="  ^fg(#FF8d8e)^i(./dzen_icons/temp.xbm) ^fg(#F8F8F8)${CPU_TEMP}"
USER_NAME=`whoami`
USER_FIELD="^fg(#F2F1EF) ^i(./dzen_icons/cat.xbm) ${USER_NAME}"

echo -e "   ^fg(#F4D03F)^i(./dzen_icons/grid.xbm) bspwm ${USER_FIELD} $CPU_INFO $MEM_INFO $CPU_TEMP_INFO"
