#!/bin/bash
cd $(dirname $0)
source $(dirname $0)/config

if [[ $(pgrep -cx panel | wc -l) -gt 1 ]] ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc control --subscribe > "$PANEL_FIFO" &
echo "T" > "$PANEL_FIFO" &
./right_system_info &
./right_one_sec_info &
./left_system_info &
./left_one_sec_info &

./panel_bar < "$PANEL_FIFO" \
    | dzen2 -x 0 -y 0 -ta l \
    -bg "$COLOR_BACKGROUND" \
    -fg "$COLOR_FOREGROUND" \
    -fn "$FONT1" \
    -h  "$PANEL_HEIGHT" &
wait
