#!/bin/bash
PWD=$(dirname $(readlink -f $0))

source $PWD/config

WIFI=$($PWD/wifi)
VOLS=$($PWD/vols)
BATT=$($PWD/battery)
CLOCK=$(date '+%Y/%m/%d %H:%M:%S')

echo "^p(_RIGHT)^p(-290)$BATT $VOLS $WIFI ^fg(#fff)^i(${ICON}clock.xbm) $CLOCK"
