import = [
    "~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"
]

[font]
size = 8

[font.normal]
family = "Hack"

[window]
decorations = "full"
padding = { x = 3, y = 3 }
dynamic_padding = true
opacity = 0.1

[window.dimensions]
columns = 184
lines = 46

[keyboard]
bindings = [
    { key = "N", mods = "Control|Shift", action = "CreateNewWindow"},
    { key = "N", mods = "Control", action = "SpawnNewInstance"},
    { key = "T", mods = "Control|Shift", action = "CreateNewTab"},
]
