#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
# completion
fpath=(~/.zsh.d/site-functions $fpath)
fpath=(~/.zsh.d/zsh-completions_dir/src $fpath)

# setting termite
export TERM=xterm-256color
#if [[ $TERM == xterm-termite ]]; then
. /etc/profile.d/vte.sh
#fi

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# My configuration
fpath+=(~/.zsh.d/site-functions $fpath)
fpath+=(~/.zsh.d/zsh-completions/src $fpath)

# Auto rehash
zstyle ':completion:*' rehash true

# Alias
alias be='bundle exec'
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias yao='yaourt'
alias g='git'
alias gad='git add'
alias gt='git status'
alias gtt='git status -uno'
alias glogo='git log --oneline'
alias glog='git log'
alias gpul='git pull'
alias gpus='git push'
alias globi='hub browse kayac/nakamap'
alias ojisan='cd $HOME/programs/ruby/animeojisan'
alias u27='cd $HOME/programs/erlang/u27'
alias r3='rebar3'
alias jnry='cd $HOME/python/junray-server'
alias vim='nvim'

# Alias
alias nkmp='cd $WEB'
alias mnth='cd $GOPATH/src/github.com/kayac/month'
alias mnthb='cd $GOPATH/src/github.com/kayac/month-baal'

# Global Alias
alias -g B='`git branch | fzf --reverse --ansi --prompt "git branch> " | head -n 1 | sed -e "s/^\*\s*//g"`'
alias -g T='`git branch -r | fzf --reverse --ansi --prompt "git remote branch> " | head -n 1 | sed -e "s/^\*\s*//g"`'
alias -g S='`git status -s | fzf -m --reverse --ansi --prompt "git status> " | sed -e "s/^\s*\S*\s*//g"`'

# Git alias
alias g='git'
alias gt='git status'
alias local-branch-clean='git checkout master && git branch --merged | grep -v master | xargs -I % git branch -d %'

# Erlang alias
alias r3='rebar3'

# Lua path
export LUA_PATH='/home/tkyshm/.luarocks/share/lua/5.3/?.lua;/home/tkyshm/.luarocks/share/lua/5.3/?/init.lua;/usr/share/lua/5.3/?.lua;/usr/share/lua/5.3/?/init.lua;/usr/lib/lua/5.3/?.lua;/usr/lib/lua/5.3/?/init.lua;./?.lua;./?/init.lua'
export LUA_CPATH='/home/tkyshm/.luarocks/lib/lua/5.3/?.so;/usr/lib/lua/5.3/?.so;/usr/lib/lua/5.3/loadall.so;./?.so'

# Java path
#export JAVA_HOME=/opt/jdk1.8

# Erlang Path
export ERLCH_BIN=$HOME/.erlch/bin
export ERL_LIBS=$HOME/erlang/lib/proper
export LC_CTYPE=ja_JP.UTF-8
export PATH=$ERLCH_BIN:$PATH

# Elixir
export PATH=$PATH:$HOME/elixir/elixir/bin

# Golang path
export GOROOT=/usr/local/go
export GOPATH=/home/tkyshm/go
export PATH=$GOPATH/bin:$GOROOT/bin:$PATH

# Android
export PATH=$PATH:/opt/android-studio/bin

# pyenv & python
#export PYENV_ROOT="$HOME/.pyenv"
#export PATH="$PYENV_ROOT/bin:$PATH"
#eval "$(pyenv init -)"
#PYTHONSTARTUP=$HOME/.pythonrc.py
#export PYTHONSTARTUP
export PYTHONUSERBASE=$HOME/local

# Node
export PATH=/usr/local/node/bin:$PATH

# PATH
export PATH=$HOME/bin:$HOME/.opam/4.04.1/bin:$PATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib

# OCaml
CAML_LD_LIBRARY_PATH="$HOME/.opam/4.04.1/lib/stublibs"; export CAML_LD_LIBRARY_PATH;
MANPATH="$HOME/.opam/4.04.1/man:"; export MANPATH;
PERL5LIB="$HOME/.opam/4.04.1/lib/perl5"; export PERL5LIB;
OCAML_TOPLEVEL_PATH="$HOME/.opam/4.04.1/lib/toplevel"; export OCAML_TOPLEVEL_PATH;

# Rust
#export PATH="$HOME/.cargo/bin:$PATH"
source $HOME/.cargo/env
#export RUST_SRC_PATH=$(rustc --print sysroot)/lib/rustlib/src/rust/src/

## Termite config
#. /etc/profile.d/vte.sh

# Flutter
export PATH=$HOME/flutter/bin:$PATH

# Android studio
export PATH=$HOME/apps/android-studio/bin:$PATH

# Ruby
export PATH=$PATH:$HOME/.gem/ruby/2.5.0/bin
