#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
# completion
fpath=(~/.zsh.d/site-functions $fpath)
fpath=(~/.zsh.d/zsh-completions_dir/src $fpath)

# setting termite
export TERM=xterm-256color
#if [[ $TERM == xterm-termite ]]; then
. /etc/profile.d/vte.sh
#fi

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# My configuration
fpath+=(~/.zsh.d/site-functions $fpath)
fpath+=(~/.zsh.d/zsh-completions/src $fpath)

# Auto rehash
zstyle ':completion:*' rehash true

# Alias
alias be='bundle exec'
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias yao='yaourt'
alias g='git'
alias gad='git add'
alias gt='git status'
alias gtt='git status -uno'
alias glogo='git log --oneline'
alias glog='git log'
alias gpul='git pull'
alias gpus='git push'
alias globi='hub browse kayac/nakamap'
alias ojisan='cd $HOME/programs/ruby/animeojisan'
alias u27='cd $HOME/programs/erlang/u27'
alias r3='rebar3'
alias jnry='cd $HOME/python/junray-server'
alias vim='nvim'

# Lua path
export LUA_PATH='/home/tkyshm/.luarocks/share/lua/5.3/?.lua;/home/tkyshm/.luarocks/share/lua/5.3/?/init.lua;/usr/share/lua/5.3/?.lua;/usr/share/lua/5.3/?/init.lua;/usr/lib/lua/5.3/?.lua;/usr/lib/lua/5.3/?/init.lua;./?.lua;./?/init.lua'
export LUA_CPATH='/home/tkyshm/.luarocks/lib/lua/5.3/?.so;/usr/lib/lua/5.3/?.so;/usr/lib/lua/5.3/loadall.so;./?.so'

# Java path
#export JAVA_HOME=/opt/jdk1.8

# Erlang Path
export ERLCH_BIN=$HOME/.erlch/bin
export ERL_LIBS=$HOME/erlang/lib/proper
# export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
export LC_CTYPE=ja_JP.UTF-8

export PATH=$PATH:$HOME/elixir/elixir/bin

# Golang path
export GOROOT=/usr/local/go
export GOPATH=/home/tkyshm/go
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin:$ERLCH_BIN

# Android
export PATH=$PATH:/opt/android-studio/bin

# pyenv & python
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
PYTHONSTARTUP=$HOME/.pythonrc.py
export PYTHONSTARTUP

# PATH
export PATH=$HOME/.opam/4.04.1/bin:$PATH:$HOME/bin
export PATH=$PATH:/usr/local/node/node-v0.12.2/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib

# OCaml
CAML_LD_LIBRARY_PATH="$HOME/.opam/4.04.1/lib/stublibs"; export CAML_LD_LIBRARY_PATH;
MANPATH="$HOME/.opam/4.04.1/man:"; export MANPATH;
PERL5LIB="$HOME/.opam/4.04.1/lib/perl5"; export PERL5LIB;
OCAML_TOPLEVEL_PATH="$HOME/.opam/4.04.1/lib/toplevel"; export OCAML_TOPLEVEL_PATH;

# Rust
export PATH="$HOME/.cargo/bin:$PATH"
export RUST_SRC_PATH=$(rustc --print sysroot)/lib/rustlib/src/rust/src/

